services:
  # .NET Core Backend API (Development with hot reload)
  backend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: taskmanagement-backend-dev
    working_dir: /src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5073
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ConnectionStrings__DefaultConnection=Data Source=/src/data/iconproject.db
      - JwtSettings__SecretKey=YourSuperSecretKeyThatIsAtLeast32CharactersLong!
      - JwtSettings__Issuer=IconProject.Api
      - JwtSettings__Audience=IconProject.Client
      - JwtSettings__ExpirationInMinutes=60
    ports:
      - "5073:5073"
    volumes:
      - ./IconProject:/src/IconProject
      - ./IconProject.Database:/src/IconProject.Database
      - ./IconProject.Common:/src/IconProject.Common
      - ./IconProject.sln:/src/IconProject.sln
      - sqlite-data-dev:/src/data
    command: dotnet watch run --project IconProject/IconProject.csproj --no-launch-profile
    networks:
      - taskmanagement-network-dev

  # React Frontend (Development with hot reload)
  frontend:
    image: node:20-alpine
    container_name: taskmanagement-frontend-dev
    working_dir: /app
    environment:
      - VITE_API_URL=http://localhost:5073
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
    networks:
      - taskmanagement-network-dev

volumes:
  sqlite-data-dev:

networks:
  taskmanagement-network-dev:
    driver: bridge
