services:
  # SQL Server Database for Development
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanagement-db-dev
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data-dev:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - taskmanagement-network-dev

  # .NET Core Backend API (Development)
  backend:
    build:
      context: .
      dockerfile: IconProject/Dockerfile
    container_name: taskmanagement-backend-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=TaskManagementDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true
      - JwtSettings__SecretKey=YourSuperSecretKeyThatIsAtLeast32CharactersLong!
      - JwtSettings__Issuer=IconProject.Api
      - JwtSettings__Audience=IconProject.Client
      - JwtSettings__ExpirationInMinutes=60
    ports:
      - "5073:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - taskmanagement-network-dev
    volumes:
      - ./IconProject:/src/IconProject:ro
      - ./IconProject.Database:/src/IconProject.Database:ro
      - ./IconProject.Common:/src/IconProject.Common:ro

  # React Frontend (Development with hot reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: taskmanagement-frontend-dev
    environment:
      - VITE_API_URL=http://localhost:5073
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - taskmanagement-network-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  sqlserver-data-dev:

networks:
  taskmanagement-network-dev:
    driver: bridge
